### ISSUE TITLE
Basic uploading

### ISSUE THREAD

**Issue by Nimmaster** [artipie/maven-adapter#1]
Use Maven libraries.
Scope: no snapshots, plugins, parents

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
You @nimmaster[/z](https://www.0crat.com/u/nimmaster) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@Nimmaster the puzzle [#7](https://github.com/artipie/maven-adapter/issues/7) is still not solved.

**Comment by 0pdd** [comment]
@Nimmaster the only puzzle [#7](https://github.com/artipie/maven-adapter/issues/7) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#1` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
