### ISSUE TITLE
StorageCache.java:42-44: Configure proxy cache with...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#104]
The puzzle `98-e282a7b7` from #98 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/78eb17d2d42f9ff2f32d36d7c976814beaabb242/src/main/java/com/artipie/maven/repository/StorageCache.java#L42-L44

The puzzle was created by @g4s8 on 23-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `98-e282a7b7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#104` is not assigned, can't get performer
