### ISSUE TITLE
Maven proxy cache doesn't work

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#105]
When loading Maven artifact via proxy for first time - it's working fine, but second attempt to load same resource returns empty response with no data and content-length = 0

**Comment by 0crat** [comment]
The job [#105](https://github.com/artipie/maven-adapter/issues/105) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/27a67d9b-50da-4b14-8f7c-c4e2c55b5b45); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.4`
