### ISSUE TITLE
Maven is broken: NoClassDefFound Header

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#109]
Maven can't find artipie/http Header class.

**Comment by 0crat** [comment]
The job [#109](https://github.com/artipie/maven-adapter/issues/109) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e9d448f5-75de-4ef0-845c-a7316cad8505); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.6`

**Comment by g4s8** [comment]
Fixed
