### ISSUE TITLE
Release to central.artipie.com

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#110]
Create workflow to release to https://central.artipie.com/artipie/maven

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.7`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.8`

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#110` is not assigned, can't get performer
