### ISSUE TITLE
Maven.java:52-54: Extract interface from this class, this...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#124]
The puzzle `113-dcb9f101` from #113 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/e0ece09aa520a995b66e87d7a7368df0144ebb06/src/main/java/com/artipie/maven/Maven.java#L52-L54

The puzzle was created by @olenagerasimova on 07-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `113-dcb9f101` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
