### ISSUE TITLE
ValidUpload.java:33-34: Implement this interface: proper...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#125]
The puzzle `113-4777d363` from #113 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/e0ece09aa520a995b66e87d7a7368df0144ebb06/src/main/java/com/artipie/maven/repository/ValidUpload.java#L33-L34

The puzzle was created by @olenagerasimova on 07-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `113-4777d363` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#131](https://github.com/artipie/maven-adapter/issues/131), [#132](https://github.com/artipie/maven-adapter/issues/132) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 30 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@0pdd the puzzle [#131](https://github.com/artipie/maven-adapter/issues/131) is still not solved; solved: [#132](https://github.com/artipie/maven-adapter/issues/132).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#143](https://github.com/artipie/maven-adapter/issues/143) is still not solved; solved: [#131](https://github.com/artipie/maven-adapter/issues/131), [#132](https://github.com/artipie/maven-adapter/issues/132).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#131](https://github.com/artipie/maven-adapter/issues/131), [#132](https://github.com/artipie/maven-adapter/issues/132), [#143](https://github.com/artipie/maven-adapter/issues/143).
