### ISSUE TITLE
Integrate HTTP client

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#128]
Integrate `artipie/http-client` into Maven proxy repository.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#138](https://github.com/artipie/maven-adapter/issues/138) is still not solved.

**Comment by g4s8** [comment]
Done in #136

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#128` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#138](https://github.com/artipie/maven-adapter/issues/138) is solved here.
