### ISSUE TITLE
Add packages and restructure classes

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#130]
I'd suggest restructure packages and rename some classes. The main idea is to introduce `asto` package and put all classes dependent from storage into this package and introduce `proxy` package for proxy-related classes. Interfaces should be placed into "root" package:
```
|-- com.artipie.maven/
  -- asto/
     |-- AstoMaven.java
     |-- RepositoryChecksums.java
     |-- AstoRp.java (renamed from RpLocal.java)
     |-- StorageCache.java
     |-- AstoUpload.java (implements ValidUpload.java, currently inner class of ValidUpload.java)
  -- proxy/
     |-- RpRemote.java
  -- metadata/
     |-- MavenMetadata.java
     |-- ArtifactsMetadata.java
  |-- ProxyCache.java
  |-- Repository.java
  |-- ValidUpload.java
  |-- Maven.java
```
`http` stays as is.

**Comment by olenagerasimova** [comment]
@g4s8 what do you think?

**Comment by g4s8** [comment]
@olenagerasimova I agree generally. But I think we also need `http` package to put all `Slice` implementation there.

**Comment by olenagerasimova** [comment]
@g4s8 `http` stays as is (I've mentioned it at the end of the initial description), I think this package is perfectly fine

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
