### ISSUE TITLE
ValidUploadAstoTest.java:93-94: Move this method to class...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#132]
The puzzle `125-7c485e22` from #125 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/2e2f3ddbf14871ed4e876b1b386fbeabbf2de593/src/test/java/com/artipie/maven/repository/ValidUploadAstoTest.java#L93-L94

The puzzle was created by @olenagerasimova on 11-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `125-7c485e22` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
