### ISSUE TITLE
MavenProxySlice.java:79-81: This class will be moved to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#138]
The puzzle `128-dad87a94` from #128 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/6371e7176584f534b3b180cdb0b4771f5b1d092f/src/main/java/com/artipie/maven/http/MavenProxySlice.java#L79-L81

The puzzle was created by @g4s8 on 13-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#138` is not assigned, can't get performer
