### ISSUE TITLE
AstoValidUploadTest.java:38-41: Refactor this test class:...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#143]
The puzzle `131-0b1cd596` from #131 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/53e78d14120d42fc260031c64db67551f41538ec/src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java#L38-L41

The puzzle was created by olenagerasimova on 13-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `131-0b1cd596` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#143` is not assigned, can't get performer
