### ISSUE TITLE
Do not start update when snapshot metadata is sent

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#144]
Snapshot artifacts [have](https://maven.apache.org/ref/3.6.3/maven-repository-metadata/repository-metadata.html) their own `maven-metadata.xml`, we do not have to start repository update when such metadata is sent. Fix `UpdateMavenSlice` accordingly, note that `maven-metadata.xml` for snapshot does not have `latest` tag, current version should be obtained from `version` tag
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.apache.maven.resolver</groupId>
  <artifactId>maven-resolver-util</artifactId>
  <versioning>
    <versions>
      <version>1.3.3-SNAPSHOT</version>
    </versions>
    <lastUpdated>20200817060818</lastUpdated>
  </versioning>
</metadata>
```
Fix `ArtifactsMetadata` to handle this situation properly, do not forget about tests.
Check [this article](https://blog.packagecloud.io/eng/2017/03/09/how-does-a-maven-repository-work/#release-and-snapshot-repositories) for more details. 
Add test with snapshort to `AstoMavenITCase` and to `MavenHttpITCase`.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#151](https://github.com/artipie/maven-adapter/issues/151) is still not solved.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#151](https://github.com/artipie/maven-adapter/issues/151) is solved here.
