### ISSUE TITLE
Proxy cache verification

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#146]
We have some broken artifacts in proxy cache, let's verify this content by sending `HEAD` request to remote before downloading artifact from cache.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#153](https://github.com/artipie/maven-adapter/issues/153) is still not solved.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @g4s8[/z](https://www.0crat.com/u/g4s8) (its creator); I won't close the order; please, re-open it and ask @g4s8[/z](https://www.0crat.com/u/g4s8) to close it
