### ISSUE TITLE
Versions comparator

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#148]
Comparing artifact versions with `Comparator.naturalOrder()` is not correct as, for example, this comparator considers `0.9` bigger than `0.10`. We need to create proper comparator, test it and use in `ArtifactsMetadata` and `MavenMetadata`.

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
