### ISSUE TITLE
ArtifactsMetadataTest.java:110-111: Extract this method...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#151]
The puzzle `144-f2081e49` from #144 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/25557b82146faaa2b51a63121a033ba5ac5ee02a/src/test/java/com/artipie/maven/metadata/ArtifactsMetadataTest.java#L110-L111

The puzzle was created by @olenagerasimova on 18-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `144-f2081e49` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#151` is not assigned, can't get performer
