### ISSUE TITLE
Avoid race conditions on adding artifact

### ISSUE THREAD

**Issue by olegmoz** [artipie/maven-adapter#178]
When artifact is added to Maven repository at same location by multiple clients race conditions are possible. To avoid them it is possible to use exclusive access to certain part of `Storage`.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@yegor256 I've just added myself as architect to `.rultor`, could you please touch the file?

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#178` is not assigned, can't get performer

**Comment by yegor256** [comment]
@olegmoz done at 038fe7d

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5`
