### ISSUE TITLE
Maven proxy tests

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#197]
Let's create tests for maven proxy: we need both unit and integration tests.

**Comment by olenagerasimova** [comment]
@genryxy it looks like I fixed maven-proxy, could you please update brunch with your proxy IT case and check whether it works?

**Comment by genryxy** [comment]
@olenagerasimova yeah, I'll update branch and check

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.6`

**Comment by olenagerasimova** [comment]
all done here

**Comment by olenagerasimova** [comment]
@olegmoz maven release failed, seems like smth is wrong with javadoc. Will ppom upgrade help or is there a way to know what is wrong exectly?

**Comment by olegmoz** [comment]
@olenagerasimova yes, probably. I will look into this ASAP

**Comment by olegmoz** [comment]
@rultor release, tag=`0.6`

**Comment by olegmoz** [comment]
@olenagerasimova @genryxy new maven release `0.6` is ready

**Comment by 0crat** [comment]
Job [#197](https://github.com/artipie/maven-adapter/issues/197) is closed, can't start order
