### ISSUE TITLE
Upgrade HTTP client and add support for authenticated proxy

### ISSUE THREAD

**Issue by olegmoz** [artipie/maven-adapter#204]
When auth support is added to HTTP client we may add authenticated access in Maven Proxy

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#204` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7`
