### ISSUE TITLE
HeadProxySlice issues

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#212]
There are two problems with `HeadProxySlice`:
1. maven-central returns 421 on requests with `Host` header and vertx adds such header, so we should not proxy headers in this slice
2. response headers (headers from proxy, from maven central for example) are not returned in response

Let's fix this and add corresponding tests.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
