### ISSUE TITLE
Update asto and clean up unused classes

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#215]
Let's update asto and remove unused classes and corresponding tests: 
1) `RpRemote` - this class functionality is now part of http-client
2) `RpAsto`and `RemoteDownloadSlice` are now part of `DownloadSlice`
3) `ProxyCache` and its implementation were moved to asto with some modifications

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#215](https://github.com/artipie/maven-adapter/issues/215), since the job is not in scope anymore
