### ISSUE TITLE
MavenProxySlice should return 404 when artifact isn't got

### ISSUE THREAD

**Issue by genryxy** [artipie/maven-adapter#219]
Maven proxy should return `404` when artifact wasn't found in cache and wasn't got via proxy.
After fixing disable test.
See #218

**Comment by 0pdd** [comment]
@genryxy the puzzle [#221](https://github.com/artipie/maven-adapter/issues/221) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#219` is not assigned, can't get performer
