### ISSUE TITLE
Validating ServiceLocator

### ISSUE THREAD

**Issue by Nimmaster** [artipie/maven-adapter#22]
`org.eclipse.aether.spi.locator.ServiceLocator` is a ServiceLocator pattern interface. It creates/retrieves services by matching service class. If the service was not yet registered it simply returns null forcing you to make a null check on each invocation.
We should hide null checks in another class implementing the interface.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#22` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
