### ISSUE TITLE
Support absent content in proxy

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/maven-adapter#222]
Let's update `asto` and support absent content by returning 404 to the client.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#224](https://github.com/artipie/maven-adapter/issues/224) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#222` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.7.1`

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#224](https://github.com/artipie/maven-adapter/issues/224) is solved here.
