### ISSUE TITLE
Readme documentation is missed

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#26]
It's not clear how to use this module, which classes to use as entry points and how to construct it. @Nimmaster  please add these details to usage section of `README.md`.

**Comment by Nimmaster** [comment]
@g4s8 why can't I close it?
Close it yourself then.

**Comment by g4s8** [comment]
@Nimmaster sure, thanks

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#26` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
