### ISSUE TITLE
Migrate upload to java.util.concurrent.Flow

### ISSUE THREAD

**Issue by Nimmaster** [artipie/maven-adapter#36]
Now it accepts InputStream, it should be refactored to `java.util.Flow.Publisher<ByteBuffer>`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#36` is not assigned, can't get performer
