### ISSUE TITLE
Implement download method

### ISSUE THREAD

**Issue by Nimmaster** [artipie/maven-adapter#37]
To introduce a method for downloading artifacts in Repository

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0pdd** [comment]
@Nimmaster the puzzle [#44](https://github.com/artipie/maven-adapter/issues/44) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#37` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@Nimmaster 2 puzzles [#44](https://github.com/artipie/maven-adapter/issues/44), [#53](https://github.com/artipie/maven-adapter/issues/53) are still not solved.

**Comment by 0pdd** [comment]
@Nimmaster all 2 puzzles are solved here: [#44](https://github.com/artipie/maven-adapter/issues/44), [#53](https://github.com/artipie/maven-adapter/issues/53).
