### ISSUE TITLE
ServiceLocatorFactory.java:60-62: Inject a...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#41]
The puzzle `10-5f36658f` from #10 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/384f888b41e99fdffcff572ee73ba44b95af4855/src/main/java/com/artipie/maven/aether/ServiceLocatorFactory.java#L60-L62

The puzzle was created by @Nimmaster on 10-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Nimmaster** [comment]
@g4s8 0pdd created a todo issue a week after the original pull request.

**Comment by Nimmaster** [comment]
Should be resolved in #51

**Comment by 0pdd** [comment]
The puzzle `10-5f36658f` has disappeared from the source code, that's why I closed this issue.
