### ISSUE TITLE
AstoTransporterTest.java:73-76: Delete temp directory....

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#44]
The puzzle `37-329dc9a9` from #37 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/40bd2fbf3623437b0278ff182da15eb45509599d/src/test/java/com/artipie/maven/aether/AstoTransporterTest.java#L73-L76

The puzzle was created by @Nimmaster on 18-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `37-329dc9a9` has disappeared from the source code, that's why I closed this issue.
