### ISSUE TITLE
AstoTransporter should set checksums for artifact resolution

### ISSUE THREAD

**Issue by Nimmaster** [artipie/maven-adapter#52]
Set checksums in Task object in `com.artipie.maven.aether.AstoTransporter#implGet` like:
```
task.setChecksum("MD5", /* get checksum from Asto */);
task.setChecksum("SHA1", /* get checksum from Asto */);
```
Now, if checksums are not set, Maven library logs warnings like:
```
WARN  o.e.a.i.impl.WarnChecksumPolicy -  Could not validate integrity of download from asto://artipie.com/maven/org/example/artifact/maven-metadata.xml
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
```
It is a place for possible optimization - to fetch a binary and its checksums in one call.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@nimmaster[/z](https://www.0crat.com/u/nimmaster) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#52` is not assigned, can't get performer
