### ISSUE TITLE
AetherRepository.java:43-46: Inject Deployer (and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#53]
The puzzle `37-15918c08` from #37 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/dacda54cdffdbd969554cd93a2d0b2f0202d030b/src/main/java/com/artipie/maven/aether/repository/AetherRepository.java#L43-L46

The puzzle was created by @g4s8 on 26-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `37-15918c08` has disappeared from the source code, that's why I closed this issue.
