### ISSUE TITLE
pom.xml:102: Remove commons usage in favor of cactoos

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#56]
The puzzle `54-9c5a8d8c` from #54 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/36e031e9b3094cdb94f33676f5425419f2b53ec0/pom.xml#L102-L102

The puzzle was created by paulodamaso on 10-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#56` is not assigned, can't get performer
