### ISSUE TITLE
Metadata.java:39-44: Implement Metadata generation....

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#57]
The puzzle `54-83abca7b` from #54 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/36e031e9b3094cdb94f33676f5425419f2b53ec0/src/main/java/com/artipie/maven/metadata/Metadata.java#L39-L44

The puzzle was created by paulodamaso on 13-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@cbab2ca4a324, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Adapter back end integration' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.51.12](https://github.com/zerocracy/farm): CID: [b02d0da8-1154-42bc-9f5e-e87fecce8235](https://www.0crat.com/footprint/CT2E6TK9B/b02d0da8-1154-42bc-9f5e-e87fecce8235), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#57](https://github.com/artipie/maven-adapter/issues/57) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/886c4e4c-707f-4e79-bf2b-145087ebfc09); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `54-83abca7b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#60](https://github.com/artipie/maven-adapter/issues/60) is still not solved.

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#60](https://github.com/artipie/maven-adapter/issues/60) is solved here.

**Comment by paulodamaso** [comment]
@g4s8 I think I didn't got paid for this one, please take a look

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/57#issuecomment-612862870))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#57](https://github.com/artipie/maven-adapter/issues/57) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@paulodamaso as I can see the payment was sent: https://www.0crat.com/footprint/CT2E6TK9B/71099498-eb44-45fd-bc4d-3be445a789ed

Can you check it in your wallet by looking for ticket id?

**Comment by paulodamaso** [comment]
@g4s8 I found it in my wallet, thank you
