### ISSUE TITLE
Metadata.java:39-44: Continue to implement metadata...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#60]
The puzzle `57-0a27a98f` from #57 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/c5a5fc70c47a948f50a1cce0a62e151568effeaa/src/main/java/com/artipie/maven/metadata/Metadata.java#L39-L44

The puzzle was created by paulodamaso on 23-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#60](https://github.com/artipie/maven-adapter/issues/60) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/357ca3a9-a78a-4ab5-8b65-0fe8f4ed2ca7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/60#issuecomment-604118645))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#60](https://github.com/artipie/maven-adapter/issues/60), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/60#issuecomment-604118645))

@carlosmiranda Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by g4s8** [comment]
@paulodamaso this ticket is most important in this module (boosted), we need to get working MVP with maven metadata as soon as possible. Let me know if you need something from my side.

**Comment by 0crat** [comment]
The job [#60](https://github.com/artipie/maven-adapter/issues/60) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/83667d9f-838c-4c55-bdf5-3991d851cdbd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/artipie/maven-adapter/issues/60#issuecomment-604924336))

@g4s8 Boost 4x was set for [#60](https://github.com/artipie/maven-adapter/issues/60)

**Comment by paulodamaso** [comment]
@g4s8 I'm working on it. I chose to use `Xembly` to build the XML but I've come across a bug in the library (https://github.com/yegor256/xembly/issues/64), so I'll have to make the XML building again (unless we can add the XML header to metadata test, WDYT?)

**Comment by g4s8** [comment]
@paulodamaso it's ok for the beginning. But we'll need to replace it later with some kind of stream XML parser & reader (e.g. like stax in `artipie/rpm-adapter`), since we may have huge metadata XML files, and we should not keep all files in memory to add one line.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `57-0a27a98f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`
