### ISSUE TITLE
File.java:38-40: Implement file storage using...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#62]
The puzzle `58-abf1aafd` from #58 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/d50a378793d571a0854d4e3b025c00c691bac075/src/main/java/com/artipie/maven/file/File.java#L38-L40

The puzzle was created by paulodamaso on 26-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#62](https://github.com/artipie/maven-adapter/issues/62) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0e5f37b3-747b-473c-8484-a56abfd12ef0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/62#issuecomment-609516002))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#62](https://github.com/artipie/maven-adapter/issues/62), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#62](https://github.com/artipie/maven-adapter/issues/62) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0a63ae94-f757-4b30-8aac-b736a66cf982); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #65 to be merged

**Comment by 0pdd** [comment]
The puzzle `58-abf1aafd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
