### ISSUE TITLE
Maven repository HTTP API

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#64]
Let's investigate what API methods Maven repo supports and add these methods.
Start this task in following order:
 1. Documentation update: let's add specification and references about maven repo API in README
 2. Create integration tests for API
 3. Implement API methods.

Try to decompose this task as much as possible using todos (e.g. one todo per API)

**Comment by 0crat** [comment]
The job [#64](https://github.com/artipie/maven-adapter/issues/64) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ce8f6b72-c994-4fe9-a182-df781ea9b1f2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/64#issuecomment-609516015))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#64](https://github.com/artipie/maven-adapter/issues/64), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#64](https://github.com/artipie/maven-adapter/issues/64) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3c43e094-4b88-47fb-a3f5-204e96c50721); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@g4s8 I've tried to find something about Maven repo API and [this](https://search.maven.org/classic/#api) is what I found, is it what you meant?

**Comment by g4s8** [comment]
@ammaratef45 not exactly: first, we need HTTP endpoints for downloading and uploading (publishing) artifacts, so client `mvn` will be able to deploy an artifact using `mvn deploy` command and use this dependency then.

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/64#issuecomment-609871115))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#64](https://github.com/artipie/maven-adapter/issues/64), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/64#issuecomment-609871115))

@ammaratef45 Job refused in 14 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#64](https://github.com/artipie/maven-adapter/issues/64) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9954ed00-4757-4337-9b6d-8139d1a1d317); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 here is my current understanding

For downloading:
- maven only relies on typical ftp/http file serving and the existence of well known files containing metadata, there are no maven-specific HTTP endpoints as in, say, Docker

For uploading:
- maven can either use normal file publishing mean (such as ftp upload, webdav PUT, etc) as long as the uploaded files respect the metadata
  - this means that adding new artefact to an existing reposirty entails updating the content of an existing metadata file
- maven can also relies on provider dedicated plugins
  - the most well known being the nexus-staging-maven-plugin (see https://central.sonatype.org/pages/apache-maven.html), that allows to push new artefact to an existing sonatype repository

For artipie, the question is: what do we want to use for upload?

How should we proceed from here? Should I write this into the README (once the decision is made for the mean of upload) and add new todos (can we add todos directly into the README?)

**Comment by victornoel** [comment]
@0crat wait for ARC

**Comment by g4s8** [comment]
> @g4s8 here is my current understanding
> 
> For downloading:
> 
>     * maven only relies on typical ftp/http file serving and the existence of well known files containing metadata, there are no maven-specific HTTP endpoints as in, say, Docker
> 
> 
> For uploading:
> 
>     * maven can either use normal file publishing mean (such as ftp upload, webdav PUT, etc) as long as the uploaded files respect the metadata
>       
>       * this means that adding new artefact to an existing reposirty entails updating the content of an existing metadata file
> 
>     * maven can also relies on provider dedicated plugins
>       
>       * the most well known being the nexus-staging-maven-plugin (see https://central.sonatype.org/pages/apache-maven.html), that allows to push new artefact to an existing sonatype repository
> 
> 
> For artipie, the question is: what do we want to use for upload?
> 
> How should we proceed from here? Should I write this into the README (once the decision is made for the mean of upload) and add new todos (can we add todos directly into the README?)

@victornoel we need to determinate what HTTP we need for downloading and uploading artifact. E.g. what HTTP methods and paths uses `mvn` client to download dependency? What HTTP it uses to upload (`mvn deploy`)? We support only HTTP protocol, no need to support FTP or others. So this task is mostly about the research, since I don't know exactly what HTTP endpoints should be implemented.

**Comment by victornoel** [comment]
@g4s8 ok, I understood that, so it's good. How do you want me to deliver the first results? In the README? Can I put todos in it? Do you want me to validate with you the choices I make here first?

**Comment by g4s8** [comment]
@victornoel yes, readme would be good. You can put todos in readme using HTML comments:
```md
<!--
@todo #1:30min Continue someting...
-->
```
> Do you want me to validate with you the choices I make here first?

Please ping me in the PR and I'd add some comments if needed.

**Comment by g4s8** [comment]
@0crat continue

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/64#issuecomment-612068084))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#64](https://github.com/artipie/maven-adapter/issues/64) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2364%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/64#issuecomment-612128282))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#64](https://github.com/artipie/maven-adapter/issues/64) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2364%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat wait for #67 to be merged

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72) are still not solved.

**Comment by victornoel** [comment]
@g4s8 this issue can now be closed, the work continue in the todos added via #67 :)

**Comment by g4s8** [comment]
@victornoel thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77) are still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#72](https://github.com/artipie/maven-adapter/issues/72) is still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71), [#77](https://github.com/artipie/maven-adapter/issues/77).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#83](https://github.com/artipie/maven-adapter/issues/83), [#84](https://github.com/artipie/maven-adapter/issues/84), [#85](https://github.com/artipie/maven-adapter/issues/85) are still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#84](https://github.com/artipie/maven-adapter/issues/84), [#91](https://github.com/artipie/maven-adapter/issues/91) are still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77), [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#84](https://github.com/artipie/maven-adapter/issues/84), [#99](https://github.com/artipie/maven-adapter/issues/99) are still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77), [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#84](https://github.com/artipie/maven-adapter/issues/84) is still not solved; solved: [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77), [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91), [#99](https://github.com/artipie/maven-adapter/issues/99).

**Comment by 0pdd** [comment]
@g4s8 all 8 puzzles are solved here: [#71](https://github.com/artipie/maven-adapter/issues/71), [#72](https://github.com/artipie/maven-adapter/issues/72), [#77](https://github.com/artipie/maven-adapter/issues/77), [#83](https://github.com/artipie/maven-adapter/issues/83), [#84](https://github.com/artipie/maven-adapter/issues/84), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91), [#99](https://github.com/artipie/maven-adapter/issues/99).
