### ISSUE TITLE
Link to travis badge in README is incorrect

### ISSUE THREAD

**Issue by victornoel** [artipie/maven-adapter#68]
I noticed the link to the travis badge is incorrect in the README, it points to another repository

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, fixed: https://github.com/artipie/maven-adapter/commit/d2edb7468c9579d644c59763d4be4cfbc1632fde

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#68` is not assigned, can't get performer

**Comment by victornoel** [comment]
@g4s8 too bad the link points to the svg instead of the build page

**Comment by g4s8** [comment]
@victornoel oops, fixed

**Comment by victornoel** [comment]
@g4s8 :+1: btw, did you notice this latest commit failed the build, it is the same error that happened in #67...

**Comment by victornoel** [comment]
> @g4s8 +1 btw, did you notice this latest commit failed the build, it is the same error that happened in #67...

@g4s8 see #70 for the explanation and a proposed fix
