### ISSUE TITLE
pom.xml file is not extending the common artipie ppom parent

### ISSUE THREAD

**Issue by victornoel** [artipie/maven-adapter#69]
It seems the parent was missed in the maven-adapter `pom.xml` file.

So most of the configurations coming from it and jcabi-parent are missing.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 also I think the compiler configuration would be better with a `combine.children` of `append` on its `testExcludes` to get the default ones from jcabi-parent:
```
<testExcludes combine.children="append">
```

**Comment by 0crat** [comment]
The job [#69](https://github.com/artipie/maven-adapter/issues/69) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e61c51ae-2f71-40d7-ac19-9854f8e5bb8d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/69#issuecomment-612957780))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#69](https://github.com/artipie/maven-adapter/issues/69), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/69#issuecomment-612957780))

@ammaratef45 Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#69](https://github.com/artipie/maven-adapter/issues/69) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2c624770-0f6e-4ad5-b144-8558da3fdb14); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@carlosmiranda please do not forget to setup the test logging as in the other projects too (by having the log4j.properties file, jcabi parent will activate the right dependencies) because right now the test logs are extremely verbose, it's really bothering.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@victornoel @g4s8 see PR #76.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #76.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/69#issuecomment-618275141))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#69](https://github.com/artipie/maven-adapter/issues/69) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `DEV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2369%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by carlosmiranda** [comment]
@victornoel done in #76, may we close now?

**Comment by victornoel** [comment]
@carlosmiranda I'm sorry but you forgot to remove the extra slf4 implementation from the pom as requested, see https://github.com/artipie/maven-adapter/issues/69#issuecomment-615887872, https://github.com/artipie/maven-adapter/pull/76#issuecomment-618321711 and https://github.com/artipie/maven-adapter/blob/266207df9ef358b224fc06718fc7f859c6e35a6f/pom.xml#L87-L92

**Comment by carlosmiranda** [comment]
@victornoel it's not there anymore. @g4s8 removed it in https://github.com/artipie/maven-adapter/pull/78/files too.

**Comment by victornoel** [comment]
@carlosmiranda perfect, I missed that :)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
