### ISSUE TITLE
OptionalAssertions.java:35-38: We added class...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#7]
The puzzle `1-539b0424` from #1 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/6baf3ebe6972fbded3f4b17e607cc00c001301a1/src/test/java/com/artipie/maven/test/OptionalAssertions.java#L35-L38

The puzzle was created by Nimmaster on 30-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-539b0424` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#7` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
