### ISSUE TITLE
AstoFileTest is missing call to get for CompletableFuture

### ISSUE THREAD

**Issue by victornoel** [artipie/maven-adapter#70]
Apparently the build fails from time to time (see #67 and https://github.com/artipie/maven-adapter/issues/68#issuecomment-612866491).

The problem is that the `AstoFileTest` tests are using `asto.save` that returns a `CompletableFuture` and `get` is not called on it, so the test does not wait for the future to complete before continuing.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#70](https://github.com/artipie/maven-adapter/issues/70) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ebaa231a-8e76-4bfd-b400-a184cae99455); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso thx

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
