### ISSUE TITLE
README.md:35-38: Continue working in the Maven HTTP API...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#71]
The puzzle `64-a4ea9323` from #64 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/2a0fdc0c6fc82fac672a79afd070cd30e364421d/README.md#L35-L38

The puzzle was created by Victor Noël on 11-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/maven-adapter/issues/71#issuecomment-614476395))

@g4s8 The job [#71](https://github.com/artipie/maven-adapter/issues/71) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9dd7bb99-4ffe-432a-a688-192993405d58); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #75 to be merged

**Comment by 0pdd** [comment]
The puzzle `64-a4ea9323` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#77](https://github.com/artipie/maven-adapter/issues/77) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#77](https://github.com/artipie/maven-adapter/issues/77) is solved here.
