### ISSUE TITLE
README.md:46-50: Continue working in the Maven HTTP API...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#72]
The puzzle `64-cc923fd8` from #64 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/2a0fdc0c6fc82fac672a79afd070cd30e364421d/README.md#L46-L50

The puzzle was created by Victor Noël on 11-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/maven-adapter/issues/72) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/aa42bb88-c89b-449c-a2b5-6f0114bcb8c8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso see #75 and https://github.com/apache/maven-resolver/tree/master/maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples for some ideas as to how test upload :)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-619252393))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#72](https://github.com/artipie/maven-adapter/issues/72), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/maven-adapter/issues/72) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2e18f1df-1980-416d-b985-619fa908f577); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-619339262))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#72](https://github.com/artipie/maven-adapter/issues/72), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-619339262))

@HDouss Job refused in 8 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/maven-adapter/issues/72) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8415d587-b48a-42b1-85de-c78f208e0c89); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-620966956))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#72](https://github.com/artipie/maven-adapter/issues/72), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/maven-adapter/issues/72) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8ce9b926-9e5c-4602-b4e7-2a08adf678bc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-621252960))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#72](https://github.com/artipie/maven-adapter/issues/72), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-621252960))

@ammaratef45 Job refused in 8 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-621294188))

@g4s8 The job [#72](https://github.com/artipie/maven-adapter/issues/72) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3c817ae2-1ade-4652-8a90-3e2acd572d90); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-622347929))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#72](https://github.com/artipie/maven-adapter/issues/72) is [in scope](http://www.zerocracy.com/policy.html#14) for 16days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): User was resigned from the ticket
    * @hdouss[/z](https://www.0crat.com/u/hdouss): User was resigned from the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2372%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 from what I gather, with Maven, all the intelligence is in the client, not the server. So when deploying, the server is doing nothing more than being a simple web server.

So is this what is expected to be done here? To make everything so that `MavenSlice` is just a file-serving web server? Or is there more functionality needed, for example to create the metadata files and so on? Usually it is the maven-deploy-plugin that takes care of creating the right metadata files and then uploading them.

**Comment by g4s8** [comment]
@victornoel it seems to be true but with one note: we have to update metadata and generate checksums after new upload (using `Maven` class to generate metadata for repository)

**Comment by victornoel** [comment]
@g4s8 that's my point, I don't think maven is meant to work like that:
- you upload an artefact via an api
- the server is smart and updates the metadata to have a consistent repository

but like that:
- you generates new metadata, checksum, etc for your artefacts
  - it is the job of the maven-deploy-plugin
- you upload them via http and the server is dumb

So in practice, we just need to add an `UploadSlice` to the `MavenSlice` (I've already wrote the integration test) and the work is done to support maven-deploy-plugin (apart from things such as authentication/authorization).

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat wait for ARC answer

**Comment by g4s8** [comment]
@victornoel we have two different kinds of metadata: you're speaking about artifact metadata, it's correct that Maven clients is generating this metadata and uploading it via HTTP. But we also have repository metadata, Maven client is not able to know this kind of metadata, and we need to update only repository metadata and repository checksums. E.g. see this link as an example of repository metadata for `com.artipie.http` repository: https://repo.maven.apache.org/maven2/com/artipie/http/maven-metadata.xml

**Comment by victornoel** [comment]
@g4s8 actually also this file is uploaded by maven-deploy-plugin (I have an IT test to support this assertion): it downloads the previous one, update it and send it again.

The only way I know to decouple the act of uploading an artifact from the act of managing the repository metadata is via the usage of ad-hoc plugins such as sonatype plugin for deploy that gives the ability to have a staging area, and that let the server, via proprietary API, update the metadata of the public repository.

**Comment by g4s8** [comment]
@victornoel can we just trigger repository metadata update on upload?
 1. User uploads artifact using maven deploy plugin
 2. Artipie saves this artifact and update repository metadata file

We can start with just upload support to verify that deploy plugin is able to work with Artipie API.

**Comment by victornoel** [comment]
@g4s8 I will make a PR, but you have to understand that we can't choose how maven-deploy-plugin behave: if it decides to upload repository metadata, we can only validate them and fail if there are not valid... or ignore them and generate them ourselves? Anyway, I will create a todo that highlight those concerns.

**Comment by victornoel** [comment]
@0crat wait for #82 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #82 to be merged ([here](https://github.com/artipie/maven-adapter/issues/72#issuecomment-625910941))

@victornoel Job [#72](https://github.com/artipie/maven-adapter/issues/72) is already on hold

**Comment by 0pdd** [comment]
The puzzle `64-cc923fd8` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#83](https://github.com/artipie/maven-adapter/issues/83), [#84](https://github.com/artipie/maven-adapter/issues/84), [#85](https://github.com/artipie/maven-adapter/issues/85) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#84](https://github.com/artipie/maven-adapter/issues/84), [#91](https://github.com/artipie/maven-adapter/issues/91) are still not solved; solved: [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#84](https://github.com/artipie/maven-adapter/issues/84), [#99](https://github.com/artipie/maven-adapter/issues/99) are still not solved; solved: [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#84](https://github.com/artipie/maven-adapter/issues/84) is still not solved; solved: [#83](https://github.com/artipie/maven-adapter/issues/83), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91), [#99](https://github.com/artipie/maven-adapter/issues/99).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#83](https://github.com/artipie/maven-adapter/issues/83), [#84](https://github.com/artipie/maven-adapter/issues/84), [#85](https://github.com/artipie/maven-adapter/issues/85), [#91](https://github.com/artipie/maven-adapter/issues/91), [#99](https://github.com/artipie/maven-adapter/issues/99).
