### ISSUE TITLE
MavenHttpITCase.java:54-60: Continue working on the Maven...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#77]
The puzzle `71-c580cc48` from #71 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/5b28adac2ca120045ea9b7c0fa5205949d376ccb/src/test/java/com/artipie/maven/MavenHttpITCase.java#L54-L60

The puzzle was created by @g4s8 on 23-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#77](https://github.com/artipie/maven-adapter/issues/77) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0eb43cf1-0bda-4bba-a373-7ad505e95423); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by 0pdd** [comment]
The puzzle `71-c580cc48` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`
