### ISSUE TITLE
Add Basic auth to maven adapter

### ISSUE THREAD

**Issue by IlyaMoskva** [artipie/maven-adapter#79]
Use http v8.4

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@IlyaMoskva PR was merged, thanks.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#79` is not assigned, can't get performer
