### ISSUE TITLE
Snapshot repository support

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#81]
Let's support snapshot repositories. Start with investigating how snapshot repository works (add it to the readme), then implement integration tests, then actual implementation.

**Comment by 0crat** [comment]
The job [#81](https://github.com/artipie/maven-adapter/issues/81) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/35965dad-b305-49d3-b9ff-403602f7d6e6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-625659085))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#81](https://github.com/artipie/maven-adapter/issues/81), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-625659085))

@carlosmiranda Job refused in 23 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#81](https://github.com/artipie/maven-adapter/issues/81) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1b6fab62-b78c-4d23-8a11-9c56f71443ec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 I've made a brief research on snapshot repositories and I've come to the following [link](https://blog.packagecloud.io/eng/2017/03/09/how-does-a-maven-repository-work/#release-and-snapshot-repositories), but I don't think it's a good idea to add it to `README.md` right now: this file has too much leftovers from previous implementation that adding new info to would just mess it more. I propose a cleanup of the `README.md` file before we add more info to it, WDYT?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@paulodamaso I agree, but I don't think it's in scope of this ticket. Can you please submit separate ticket and describe what to clean up and I'll add it to scope

**Comment by paulodamaso** [comment]
@0crat wait I've lost some days due https://github.com/artipie/maven-adapter/issues/81#issuecomment-627700715

**Comment by paulodamaso** [comment]
@g4s8 filed an issue, please take a look at https://github.com/artipie/maven-adapter/issues/89

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/maven-adapter/issues/89

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/artipie/maven-adapter/issues/89 ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-633305959))

@paulodamaso Job [#81](https://github.com/artipie/maven-adapter/issues/81) is already on hold

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-635068842))

@paulodamaso This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#81](https://github.com/artipie/maven-adapter/issues/81) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2381%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 please assign it to me

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-636797816))

@g4s8 The job [#81](https://github.com/artipie/maven-adapter/issues/81) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a923d2b5-24b9-4d02-8b40-463e9068faec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #101

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#81](https://github.com/artipie/maven-adapter/issues/81) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/630ce7ed-a072-474a-af18-3d99f2146880); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso @g4s8 has this been incorrectly assigned to me?

**Comment by victornoel** [comment]
@0crat wait

**Comment by g4s8** [comment]
> @paulodamaso @g4s8 has this been incorrectly assigned to me?

@victornoel I've assigned this ticket to you because @paulodamaso is not responding in PR comments for too long.

**Comment by victornoel** [comment]
@g4s8 I will refuse this job, I think @paulodamaso answered in the PR, so you want to assign to him again maybe before I refuse and it gets assigned to a third person?

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/maven-adapter/issues/81#issuecomment-654126069))

@g4s8 The job [#81](https://github.com/artipie/maven-adapter/issues/81) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2387dcd8-bb6b-4936-8b93-ee33aeccaa2b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 I'll look into it today, sorry for the absence

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#112](https://github.com/artipie/maven-adapter/issues/112) is still not solved.

**Comment by g4s8** [comment]
@paulodamaso PR #101 was merged, thanks.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b57b9f35-7df5-4955-ab20-737d5c5791ad, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/maven-adapter#81] declared for identity constraint of element "speed".
```

[0.54.5](https://github.com/zerocracy/farm): CID: [6b9e2402-4fbb-4047-b80e-1fd827b2a41a](https://www.0crat.com/footprint/CT2E6TK9B/6b9e2402-4fbb-4047-b80e-1fd827b2a41a), Type: "Order was finished"

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#112](https://github.com/artipie/maven-adapter/issues/112) is solved here.
