### ISSUE TITLE
MavenSlice.java:45-47: Continue working on the Maven HTTP...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#83]
The puzzle `72-b493e50d` from #72 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/c7d545c0c1938e31fbaf3161f27e17502608f4d3/src/main/java/com/artipie/maven/http/MavenSlice.java#L45-L47

The puzzle was created by Victor Noël on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#83](https://github.com/artipie/maven-adapter/issues/83) assigned to @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/00f56389-960a-4e27-af32-e044eccbe337); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.1`

**Comment by IlyaMoskva** [comment]
@g4s8 May we close it?

**Comment by g4s8** [comment]
@IlyaMoskva yes, thanks

**Comment by 0crat** [comment]
Job [#83](https://github.com/artipie/maven-adapter/issues/83) is not in the agenda of @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), can't set title

**Comment by 0crat** [comment]
Job [#83](https://github.com/artipie/maven-adapter/issues/83) is not in the agenda of @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
