### ISSUE TITLE
MavenHttpITCase.java:70-72: For some unknown reason the...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#84]
The puzzle `72-e21c7763` from #72 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/c7d545c0c1938e31fbaf3161f27e17502608f4d3/src/test/java/com/artipie/maven/MavenHttpITCase.java#L70-L72

The puzzle was created by Victor Noël on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#84](https://github.com/artipie/maven-adapter/issues/84) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2193a12f-fcc6-4eea-bf8c-c4eb3c835b80); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/84#issuecomment-627764014))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#84](https://github.com/artipie/maven-adapter/issues/84), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#84](https://github.com/artipie/maven-adapter/issues/84) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f429feb0-be39-40fc-978d-46e8582029d0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/84#issuecomment-627812182))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#84](https://github.com/artipie/maven-adapter/issues/84), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/84#issuecomment-627812182))

@victornoel Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0pdd** [comment]
The puzzle `72-e21c7763` has disappeared from the source code, that's why I closed this issue.
