### ISSUE TITLE
MavenHttpITCase.java:158-164: For now the generation of...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#85]
The puzzle `72-9e640b6a` from #72 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/c7d545c0c1938e31fbaf3161f27e17502608f4d3/src/test/java/com/artipie/maven/MavenHttpITCase.java#L158-L164

The puzzle was created by Victor Noël on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#85](https://github.com/artipie/maven-adapter/issues/85) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/cccea600-b558-4e9a-93dc-9557f1360f70); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `72-9e640b6a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#91](https://github.com/artipie/maven-adapter/issues/91) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#99](https://github.com/artipie/maven-adapter/issues/99) is still not solved; solved: [#91](https://github.com/artipie/maven-adapter/issues/91).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#91](https://github.com/artipie/maven-adapter/issues/91), [#99](https://github.com/artipie/maven-adapter/issues/99).
