### ISSUE TITLE
README.md cleanup

### ISSUE THREAD

**Issue by paulodamaso** [artipie/maven-adapter#89]
`README.md` has leftovers from previous implementations which does not apply to current project structure. We need to do a cleanup, removing or correcting the following items:
- "maven-adapter": correct project description, it does not depends on 'org.apache.maven' and 'org.eclipse.aether' anymore
- "how it works": we have some documentation on how maven works in "files" and "layout" topics, maybe we could leave them here for documentation purposes
- "a developer's entrypoint": "storaqge lifecycle" topic is outdated and could be removed
- "maven library abstract": is outdated and can be removed also

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#89](https://github.com/artipie/maven-adapter/issues/89) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3546353a-bd38-446b-8869-4fc380399524); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/89#issuecomment-633668103))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#89](https://github.com/artipie/maven-adapter/issues/89), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/89#issuecomment-633668103))

@victornoel Job refused in 7 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by paulodamaso** [comment]
@g4s8 please assign me

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/maven-adapter/issues/89#issuecomment-633908418))

@g4s8 The job [#89](https://github.com/artipie/maven-adapter/issues/89) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2d062ac2-2919-452f-b2a9-c6f74c2f5a22); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#89` is not assigned, can't get performer

**Comment by paulodamaso** [comment]
@g4s8 please take a look at this one

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/maven-adapter/issues/89#issuecomment-640481682))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#89](https://github.com/artipie/maven-adapter/issues/89) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fmaven-adapter%2389%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat pay 30min @paulodamaso
