### ISSUE TITLE
Repository.java:35-44: Continue working on implementing a...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#95]
The puzzle `92-1b44735d` from #92 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/b27e9357fe708110c1e6c1df13546da285d581df/src/main/java/com/artipie/maven/repository/Repository.java#L35-L44

The puzzle was created by Victor Noël on 06-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#95](https://github.com/artipie/maven-adapter/issues/95) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f284dc20-8307-491e-b8fe-43233648371e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `92-1b44735d` has disappeared from the source code, that's why I closed this issue.
