### ISSUE TITLE
RpRemote.java:48-50: Introduce constructor parameters to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#97]
The puzzle `92-97bb0a49` from #92 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/b27e9357fe708110c1e6c1df13546da285d581df/src/main/java/com/artipie/maven/repository/RpRemote.java#L48-L50

The puzzle was created by Victor Noël on 06-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#97](https://github.com/artipie/maven-adapter/issues/97) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b4769864-04ed-4b2e-8ec5-99d8664ef79d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/97#issuecomment-646967165))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#97](https://github.com/artipie/maven-adapter/issues/97), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/97#issuecomment-646967165))

@victornoel Job refused in 20 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#97](https://github.com/artipie/maven-adapter/issues/97) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3d83ff11-12dd-4841-af73-2d4ca4f0c8b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/97#issuecomment-662293605))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#97](https://github.com/artipie/maven-adapter/issues/97), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0pdd** [comment]
The puzzle `92-97bb0a49` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#97` is not assigned, can't get performer
