### ISSUE TITLE
RpRemote.java:51-53: Add support for caching the...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#98]
The puzzle `92-c03a78f8` from #92 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/b27e9357fe708110c1e6c1df13546da285d581df/src/main/java/com/artipie/maven/repository/RpRemote.java#L51-L53

The puzzle was created by Victor Noël on 06-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#98](https://github.com/artipie/maven-adapter/issues/98) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/22815aee-c13f-4f0e-abc9-083cfbcd9c08); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#104](https://github.com/artipie/maven-adapter/issues/104) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.2`

**Comment by 0pdd** [comment]
The puzzle `92-c03a78f8` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.3`

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.3`

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#104](https://github.com/artipie/maven-adapter/issues/104) is solved here.
