### ISSUE TITLE
Maven.java:43-51: Generate valid checksums on metadata...

### ISSUE THREAD

**Issue by 0pdd** [artipie/maven-adapter#99]
The puzzle `91-f4650219` from #91 has to be resolved: 

https://github.com/artipie/maven-adapter/blob/ed81f6cb670ad8c38b65ebb25545279a007b7d37/src/main/java/com/artipie/maven/Maven.java#L43-L51

The puzzle was created by paulodamaso on 31-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/99#issuecomment-643740123))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#99](https://github.com/artipie/maven-adapter/issues/99), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#99](https://github.com/artipie/maven-adapter/issues/99) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2d472b84-ac91-4851-be22-6b398dc1edb9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/maven-adapter/issues/99#issuecomment-662292714))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#99](https://github.com/artipie/maven-adapter/issues/99), please stop working. Reason for job resignation: Order was cancelled

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0pdd** [comment]
The puzzle `91-f4650219` has disappeared from the source code, that's why I closed this issue.
